#!/usr/bin/env bash


PROJECT=$(git rev-parse --show-toplevel)
cd $PROJECT
SFILES=$(git diff --cached --name-only --diff-filter=ACMR HEAD | grep \\.php)
TMP_DIR=$PROJECT."/tmp"

# Determine if a file list is passed
if [ "$#" -ne 0 ]
then
    exit 0
fi
echo "Checking PHP Lint..."
for FILE in $SFILES
do
    php -l -d display_errors=0 $FILE
    if [ $? != 0  ]
    then
        echo "Fix the syntax error before commit."
        exit 1
    fi
    FILES="$FILES $PROJECT/$FILE"
done

echo "code style check and fixing..."
PHP_CS_FIXER="vendor/bin/php-cs-fixer"
HAS_PHP_CS_FIXER=false

if [ -x vendor/bin/php-cs-fixer ]; then
    HAS_PHP_CS_FIXER=true
fi

if $HAS_PHP_CS_FIXER; then
    git status --porcelain | grep -e '^[AM]\(.*\).php$' | cut -c 3- | while read line; do
        $PHP_CS_FIXER fix "$line";
        git add "$line";
    done
else
    echo ""
    echo "php-cs-fixer was not found, please run:"
    echo ""
    echo "  composer update --dev"
    echo ""
fi
